### PR TITLE
Upgrade to Rust edition 2018

### PR DESCRIPTION
**Pull request by MaloJaffre**
This brings various improvements to the language, like C++17.

The small changes are necessary to pass the tests.

### CODE REVIEW

**Comment by seirl** [comment]
We strive to be compatible with debian stable. Support for C++17 is a bit primitive in GCC6. Is this flag supported in the latest debian stable version of rustc?

**Comment by MaloJaffre** [comment]
This flag isn't supported in debian stable (rustc 1.24.1), but Rust is evolving rapidly and there is a lag of 11 versions compared to archlinux (rustc 1.35.0), with significant improvements for the language, especially with this flag enabled.

**Comment by seirl** [comment]
Hmm, right... I'm willing to make an exception because we're so close to the Debian Buster release, and this is isolated in a generator, but it's really annoying for development to not be able to use Stechec2 when you're not on Archlinux.

One other possibility in the future could be to override the RUSTC options in the contestant Makefile?

**Comment by alarsyo** [comment]
According to https://packages.debian.org/buster/rustc this is no longer an issue (Support for the 2018 edition was [stabilized in Rust 1.31](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html), and Debian stable now ships `rustc` v1.34)

**Pull request merged**
